# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('amigo_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_if', models.ImageField(upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('my_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateTimeField()),
                ('sexo', models.CharField(max_length=12)),
                ('user', models.CharField(max_length=25)),
                ('psswd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='My_blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publi', models.DateTimeField()),
                ('detalle', models.TextField()),
                ('amigo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.Amistad')),
            ],
        ),
        migrations.CreateModel(
            name='My_perfil',
            fields=[
                ('perfil_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=25)),
                ('my_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.Me')),
            ],
        ),
        migrations.AddField(
            model_name='my_blog',
            name='perfil_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.My_perfil'),
        ),
        migrations.AddField(
            model_name='fotos',
            name='perfil_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.My_perfil'),
        ),
        migrations.AddField(
            model_name='amistad',
            name='my_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.Me'),
        ),
    ]
